// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    partial class ParksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Parks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Location = "Oregon",
                            Name = "Crater Lake",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            Location = "California",
                            Name = "Yosemite National Park",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            Location = "Utah",
                            Name = "Bryce Canyon Nation Park",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            Location = "Utah",
                            Name = "Zion National Park",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 5,
                            Location = "Oregon",
                            Name = "Blue Lake",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 6,
                            Location = "California",
                            Name = "Merced's Applegate Park Zoo",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 7,
                            Location = "Oregon",
                            Name = "Fairview Community Park",
                            Type = "City"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
